### ISSUE TITLE
Lock down bugs.php.net to only developer accounts

### ISSUE THREAD

**Issue by damianwadley** [php/web-bugs#114]
Nearly all public activity on bugs.php.net is now spam - which is not a rare occurrence - and most of the remainder is "me too" comments on old bugs.

It's time to pull the trigger on the next stage of transitioning to GitHub Issues: don't allow any further edits, comments, uploads, or other activity except by php.net developer accounts. If there's still "BuT iT's OwNeD bY mIcRoSoFt!!1!" concerns then there could easily be a config flag that enables/disables the lockdown.

**Comment by Girgias** [comment]
I know we had a couple of discussion with @cmb69 about this. The main blocker was security issues. But AFAIK those can now be handled on GitHub too.

**Comment by damianwadley** [comment]
True, but even if we're not ready for that leap just yet, doesn't restricting to php.net accounts still allow work with security reports? Speaking as someone who hasn't worked with those. If not then they could just, you know, be an exception to the rule.

**Comment by nikic** [comment]
https://github.com/php/web-bugs/commit/717f16a6d9c1a309a5ea5dad78a7a0ab0ce97429 should help with the spam.

**Comment by cmb69** [comment]
> [717f16a](https://github.com/php/web-bugs/commit/717f16a6d9c1a309a5ea5dad78a7a0ab0ce97429) should help with the spam.

Well, they already worked around that, by prepending "github" to the URL.

And a lot of recent spam is using the "upload patch" feature. I wanted to suggest to disable that altogether, but just found this ticket.

> The main blocker was security issues. But AFAIK those can now be handled on GitHub too.

Actually, it is no longer possible to submit any new reports (security related or otherwise; see https://bugs.php.net/report.php).

> It's time to pull the trigger on the next stage of transitioning to GitHub Issues: don't allow any further edits, comments, uploads, or other activity except by php.net developer accounts.

After thinking about this, I fully agree. If people have really something to say about an old bug, it is not that unlikely that they open a GH issue, so we can basically transfer relevant tickets to GH over time. There are better ways to spend time, than to remove spam.

**Comment by nikic** [comment]
Yes, I think it's fine to limit bugs.php.net to php.net accounts at this point.

**Comment by cmb69** [comment]
I'm quite surprised to have not seen any new spam on that bug tracker for almost a week. Has this issue already been resolved in some way (without touching this repo)?

**Comment by php-pulls** [comment]
Not by me doing anything actively.

**Comment by cmb69** [comment]
Is it you, @derickr? I thought that issue had been resolved.

**Comment by derickr** [comment]
Yes. It's me. Using my github email address. It worked yesterday...
